### ISSUE TITLE
Ошибка с полем в InformersModels/Part.cs во время дождя 

### ISSUE THREAD

**Issue by AVLozhechkin** [dmitry-bym/YandexWeatherApi#2]
Добрый день!

При использовании клиента во время дождя вылетает ошибка
`System.Text.Json.JsonException: 'The JSON value could not be converted to System.Int32. Path: $.forecast.parts[0].prec_mm | LineNumber: 0 | BytePositionInLine: 733.'`
Код воспроизведения простой:
```
var request = YandexWeather.CreateBuilder()
                    .UseApiKey(api_key)
                    .Build()
                    .Informers()
                    .WithLocale(WeatherLocale.ru_RU)
                    .WithLocality(new WeatherLocality(59.942668, 30.315871));

var result = await request.Send(new CancellationToken());

Console.WriteLine(JsonSerializer.Serialize(result.Data));
```
Главное, чтобы было указано место, где идёт дождь.

Связано это, как я понимаю, с ошибочно установленным типом int у поля PrecMm, так как во время дождя число осадков возвращается не целое и [во всех других классах у этого поля значение float](https://github.com/search?q=repo%3Admitry-bym%2FYandexWeatherApi+precmm&type=code).

**Comment by dmitry-bym** [comment]
released new version

**Comment by dmitry-bym** [comment]
released new version
